language: java
sudo: false
addons:
  apt:
    sources:
      - ppa:chris-lea/zeromq
      - ppa:marutter/rrutter
    packages:
      - nginx
      - libzmq3-dbg
      - libzmq3-dev
      - libzmq3
      - python-pip
      - python-dev
      - python-matplotlib
      - python-scipy
      - python-pandas
      - r-base
      - r-base-dev
jdk:
  - oraclejdk7
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
before_script:
  - export PATH=$HOME/.local/bin:$PATH
  - mkdir ~/rlibs
  - export R_LIBS=$HOME/rlibs
  - pip install ipython jinja2 tornado pyzmq --user `whoami`
  - Rscript -e "install.packages('Rserve',,'http://cran.us.r-project.org')" -l $HOME/rlibs
  - Rscript -e "install.packages('ggplot2',,'http://cran.us.r-project.org')" -l $HOME/rlibs
  - Rscript -e "install.packages('devtools',,'http://cran.us.r-project.org')" -l $HOME/rlibs
  - Rscript -e "install.packages('RJSONIO',,'http://cran.us.r-project.org')" -l $HOME/rlibs
  - Rscript -e "install.packages('RCurl',,'http://cran.us.r-project.org')" -l $HOME/rlibs
