language: java
jdk:
  - oraclejdk8
env:
  - chromeBinaryPath=/home/travis/build/twosigma/beaker-notebook/chrome-linux/chrome
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "curl -Lo chrome.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip chrome.zip"
  - "curl -Lo chromedriver.zip http://chromedriver.storage.googleapis.com/2.16/chromedriver_linux64.zip && unzip chromedriver.zip"
  - "curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -"
  - "gem install sass"
  - "sudo apt-get install -y nodejs"
  - "sudo apt-get install nginx"
  - 'ln -s /usr/bin/node /home/travis/build/twosigma/beaker-notebook/'
  - 'ln -s /usr/bin/npm /home/travis/build/twosigma/beaker-notebook/'
before_script:
  - export PATH=/home/travis/build/twosigma/beaker-notebook:$PATH
