---

- name: install squid
  sudo: yes
  apt: pkg=squid3 default_release="wheezy-backports" update_cache=true state=latest

- name: copy public cert
  sudo: yes
  copy: src=squid.public.pem dest=/etc/squid3/public.pem

- name: copy private key
  sudo: yes
  copy: src=squid.private.pem dest=/etc/squid3/private.pem

- name: set permissions on public cert
  sudo: yes
  file: path=/etc/squid3/public.pem owner=proxy group=proxy state=file

- name: set permissions on private key
  sudo: yes
  file: path=/etc/squid3/private.pem owner=proxy group=proxy state=file

- name: create squid ssl cert database folder
  sudo: yes
  file: path=/usr/local/squid3/var/lib recurse=yes state=directory

- name: create squid ssl cert database
  sudo: yes
  command: /usr/lib/squid3/ssl_crtd -c -s /usr/local/squid3/var/lib/ssl_db

- name: set permissions on squid ssl cert database
  sudo: yes
  file: path=/usr/local/squid3/var/lib/ssl_db owner=proxy group=proxy recurse=yes state=directory

- name: render squid config template
  sudo: yes
  template: src=squid.conf.j2 dest=/etc/squid3/squid.conf
  notify: reload squid

- name: configure apt to use proxy
  sudo: true
  copy: src="squid.apt.conf" dest="/etc/apt/apt.conf.d/00proxy"
