---

- name: install iptables-persistent
  sudo: yes
  apt: pkg=iptables-persistent update_cache=true state=latest

- name: enable localnet routing for all interfaces
  sudo: yes
  sysctl: name=net.ipv4.conf.all.route_localnet value=1 sysctl_set=yes state=present

- name: enable localnet routing by default
  sudo: yes
  sysctl: name=net.ipv4.conf.default.route_localnet value=1 sysctl_set=yes state=present

- name: render iptables template
  sudo: yes
  template: src=rules.v4.j2 dest=/etc/iptables/rules.v4
  notify:
    - reload iptables-persistent
