---

- name: create docker group
  sudo: yes
  group: name=docker state=present
  tags:
    - initialize
    - docker

- name: create docker directories
  sudo: yes
  file: path={{ item }} state=directory
  with_items:
    - "{{ docker_data_directory }}"
    - /etc/systemd/system/docker.service.d
  tags:
    - initialize
    - docker

- name: render docker config
  sudo: yes
  template: src={{ docker_config_file }} dest={{ item }}
  when: docker_config_file != ""
  with_items:
    - /etc/.dockercfg
    - /root/.dockercfg
  tags:
    - configure
    - docker

- name: render docker options
  sudo: yes
  template: src={{ docker_options_file }} dest=/etc/systemd/system/docker.service.d/docker.conf
  when: docker_options_file != ""
  notify:
    - reload docker options
  tags:
    - configure
    - docker

- name: enable docker service
  sudo: yes
  service: name=docker enabled=yes state=started
  tags:
    - start
    - docker
